# values.yaml (MinIO Bitnami chart)
image:
  registry: docker.io
  repository: bitnami/minio
  tag: 2025.5.24-debian-12-r5
  pullPolicy: IfNotPresent

auth:
  existingSecret: minio-auth
  existingSecretKeys:
    rootUserKey: root-user
    rootPasswordKey: root-password

  #rootUser: "minio"
  #rootPassword: "b3nt3go_minio"

mode: distributed
statefulset:
  replicaCount: 4

persistence:
  enabled: true
  storageClass: nfs-client   # Sende hangi isimse onu ya
  size: 5Gi
  accessModes:
    - ReadWriteMany          # NFS için RWX

resources:
  requests:
    cpu: "500m"
    memory: "5Gi"
  limits:
    cpu: "500m"
    memory: "5Gi"

service:
  type: NodePort
  ports:
    api: 9000
    console: 9001
  nodePorts:
    api: 30051
    console: 30050

livenessProbe:
  httpGet: { path: /minio/health/live,  port: 9000 }
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet: { path: /minio/health/ready, port: 9000 }
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

securityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
